####### Observatory Location
Observatory:
  name: "OAJ"
  lati: +40.0422222
  long: -01.0163889
  elev: 1957
  temp: 5
  prss: 800
  tizo: "UTC"

####### Config parameters
Data:
  datadir: '/home/pi/images/'

Expos:
  night: 45
  day: 0.0001


