####### Observatory Location
Observatory:
  name: "OAJ"
  lati: 40.0422222
  long: -01.0163889
  elev: 1957
  temp: 5
  prss: 800
  tizo: "UTC"

####### Instrument parameters
Instru:
  name:   'Starlight Xpress AllSk Oculus'   # Name
  camera: 'SX CCD SuperStar'
  usbtag: 'Starlight Xpress'   
  id:     'allsky'              # UPAD id
  data_dir: '/mnt/ALLSKY_USB/data/oaj/allsky'
  expo_night: 2                 #time exposure in seconds
  expo_day: 0.1                #time exposure in seconds
  sundt: 30                     # delay of time before/after sunset/sunrise
 
