####### Observatory Location
Observatory:
  name: "OAJ"
  lati: +40.0422222
  long: -01.0163889
  elev: 1957
  temp: 5
  prss: 800
  tizo: "UTC"

####### Instrument parameters
Instru:
  name:  'Oculus'
  id:    'allsky'

####### Data config
Data:
  datadir: '/home/pi/images/'
  fitsdir: 'raw'
  pngdir:  'png'
  avidir:  '/home/pi/images/avi'

Expos:
  night: 1
  day: 0.0001


