####### Observatory Location
Observatory:
  name: "OAJ"
  lati: 40.0422222
  long: -01.0163889
  elev: 1957
  temp: 5
  prss: 800
  tizo: "UTC"

####### Instrument parameters
Instru:
  name:   'StarXpress Oculus'
  camera: 'SX CCD SuperStar'
  id:     'allsky'

####### Data config
Data:
  data_dir: '/media/pi/ALLSKY_USB/data/oaj/allsky'

Expos:
  night: 1
  day: 0.0001

